version: '2'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - "5400:5400"
    depends_on:
      - redis
    environment:
      REDISINSIGHT_UI_USERNAME: admin
      REDISINSIGHT_UI_PASSWORD: admin
